version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      BASE_URL: http://localhost:9000
      DATABASE_URL: mysql://user:password@db/mydb
    volumes:
      - backend-uploads:/public/uploads

  db:
    image: mysql:5.7
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_movie
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db

volumes:
  db-data:
  backend-uploads:
