export const genresData = [
  { name: 'Action' },
  { name: 'Adventure' },
  { name: 'Comedy' },
  { name: 'Crime' },
  { name: 'Drama' },
  { name: 'Fantasy' },
  { name: 'Historical' },
  { name: 'Historical fiction' },
  { name: 'Horror' },
  { name: 'Magical realism' },
  { name: 'Mystery' },
  { name: 'Paranoid fiction' },
  { name: 'Philosophical' },
  { name: 'Political' },
  { name: 'Romance' },
  { name: 'Saga' },
  { name: 'Satire' },
  { name: 'Science fiction' },
  { name: 'Social' },
  { name: 'Thriller' },
];
